MethodLength:
  Enabled: false

Documentation:
  Enabled: false

CollectionMethods:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

LineLength:
  Exclude:
    - features/step_definitions/**/*
    - features/support/env.rb

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - script/**/*
    - db/**/*
    - config/**/*
    - tmp/**/*
    - log/**/*
    - spec/spec_helper.rb
